version: '3.8'
services:
  threat_engine:
    build: .
    container_name: cp_threat_engine
    env_file: .env
    volumes:
      - ./app/data.db:/app/data.db
    restart: always
    command: python app/main.py

  dashboard:
    build: .
    container_name: cp_dashboard
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./app/data.db:/app/data.db
    restart: always
    command: python app/dashboard.py
